name: Build and Release Felux ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ARCH: x86_64
  IMAGE_NAME: felux
  IMAGE_REPO: ghcr.io/reisaraujo-miguel
  IMAGE_TAG: latest
  VERSION: "40"
  VARIANT: Kinoite

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Build ISO
      uses: jasonn3/build-container-installer@v1.2.2
      id: build
      with:
        arch: ${{ env.ARCH }}
        image_name: ${{ env.IMAGE_NAME }}
        image_repo: ${{ env.IMAGE_REPO }}
        image_tag: ${{ env.IMAGE_TAG }}
        version: ${{ env.VERSION }}
        variant: ${{ env.VARIANT }}
        iso_name: ${{ env.IMAGE_NAME }}.iso
        enable_cache_dnf: "true"
        enable_cache_skopeo: "false"
        enable_flatpak_dependencies: "true"
        enrollment_password: "container-installer"
        flatpak_remote_name: "flathub"
        flatpak_remote_url: "https://flathub.org/repo/flathub.flatpakrepo"
        image_signed: "true"
        rootfs_size: "2"
        web_ui: "false"

    - name: Debug Output
      if: always()
      run: |
        echo "Build step outcome: ${{ steps.build.outcome }}"
        echo "Build step outputs:"
        echo "${{ toJson(steps.build.outputs) }}"

    - name: Upload ISO as artifact
      uses: actions/upload-artifact@v3
      with:
        name: felux-iso
        path: ${{ github.workspace }}/${{ steps.build.outputs.iso_name }}
        if-no-files-found: error

    - name: Get ISO version
      id: iso_version
      run: |
        ISO_VERSION=$(date +"%Y%m%d")
        echo "version=$ISO_VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: v${{ steps.iso_version.outputs.version }}
        name: Felux ISO v${{ steps.iso_version.outputs.version }}
        body: |
          Felux ISO v${{ steps.iso_version.outputs.version }} (Based on Fedora ${{ env.VERSION }})
          
          The ISO file is available as a GitHub Actions artifact due to file size limitations.
          Please download the artifact from the Actions tab of this repository.
          
          Checksum file is attached to this release.
          
          ISO Filename: ${{ steps.build.outputs.iso_name }}
        draft: false
        prerelease: false
        files: |
          ${{ github.workspace }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
