---
name: Build Release ISO

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  ARCH: x86_64
  IMAGE_NAME: felux
  IMAGE_REPO: ghcr.io/reisaraujo-miguel
  IMAGE_TAG: latest
  VERSION: "41"
  VARIANT: Kinoite

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Get Release Version
        id: get_version
        run: |
          echo "release_ver=$(cat ./version.txt)" >> $GITHUB_ENV

      - name: Build ISO
        uses: jasonn3/build-container-installer@a1ce6da2d6c1af0561bec053366d0f3aa7e38743
        id: build
        with:
          arch: ${{ env.ARCH }}
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ${{ env.IMAGE_REPO }}
          image_tag: ${{ env.IMAGE_TAG }}
          version: ${{ env.VERSION }}
          variant: ${{ env.VARIANT }}
          secure_boot_key_url: https://github.com/ublue-os/akmods/raw/main/certs/public_key.der
          enrollment_password: universalblue
          enable_cache_dnf: false
          enable_cache_skopeo: false
          iso_name: ${{ env.IMAGE_NAME }}-v${{ env.release_ver }}.iso
          flatpak_remote_name: flathub
          flatpak_remote_url: https://flathub.org/repo/flathub.flatpakrepo
          flatpak_remote_refs_dir: /github/workspace/flatpak_refs

      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
          if-no-files-found: error
          compression-level: 0

      - name: Get Artifact URL
        id: get_iso_artifact
        run: |
          iso_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          echo "iso_url=$iso_url" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          git_chglog="github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.4"
          changelog="$(go run $git_chglog --silent --next-tag v${{ env.release_ver }} v${{ env.release_ver }})"

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974
        if: success() && github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ env.release_ver }}
          name: Felux ${{ env.release_ver }}
          body: |
            ${{ env.CHANGELOG }}

            ---

            Felux ${{ env.release_ver }} (Based on Fedora ${{ env.VERSION }})

            The ISO file is available as a GitHub Actions artifact due to file size limitations.

            [Download ${{ steps.build.outputs.iso_name }}](${{ env.iso_url }})

            Note: You need to be logged in to GitHub to download the artifact.
          draft: false
          prerelease: false
          files: |
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
