---
name: Build Release ISO

on:
  workflow_run:
    workflows: ["Build Main Image"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

env:
  ARCH: x86_64
  IMAGE_NAME: felux
  IMAGE_REPO: ghcr.io/reisaraujo-miguel
  IMAGE_TAG: latest
  VERSION: "41"
  VARIANT: Kinoite

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.event != 'schedule')
    permissions:
      contents: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Get ISO Build Date
      id: iso_build_date
      run: |
        ISO_BUILD_DATE="$(date +"%Y%m%d")"
        echo "date=$ISO_BUILD_DATE" >> "$GITHUB_OUTPUT"

    - name: Build ISO
      uses: jasonn3/build-container-installer@a1ce6da2d6c1af0561bec053366d0f3aa7e38743
      id: build
      with:
        arch: ${{ env.ARCH }}
        image_name: ${{ env.IMAGE_NAME }}
        image_repo: ${{ env.IMAGE_REPO }}
        image_tag: ${{ env.IMAGE_TAG }}
        version: ${{ env.VERSION }}
        variant: ${{ env.VARIANT }}
        iso_name: ${{ env.IMAGE_NAME }}-${{ env.VERSION }}-${{ steps.iso_build_date.outputs.date }}.iso
        flatpak_remote_name: flathub
        flatpak_remote_url: https://flathub.org/repo/flathub.flatpakrepo
        flatpak_remote_refs_dir: /github/workspace/flatpak_refs

    - name: Upload ISO as artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.iso_name }}
        path: |
          ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
          ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
        if-no-files-found: error
        compression-level: 0

    - name: Format Build Date
      id: format_date
      run: echo "formatted_date=$(date -d ${{ steps.iso_build_date.outputs.date }} +"%Y/%m/%d")" >> "$GITHUB_ENV"

    - name: Create Release
      uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8
      if: success() && github.ref == 'refs/heads/main'
      with:
        tag_name: v${{ env.VERSION }}
        name: Felux ${{ env.VERSION }}
        body: |
          Felux ${{ env.VERSION }} (Based on Fedora ${{ env.VERSION }})

          last built on: ${{ env.formatted_date }}

          The ISO file is available as a GitHub Actions artifact due to file size limitations.

          [Download ISO Artifact](${{ steps.upload.outputs.artifact_url }})

          Note: You need to be logged in to GitHub to download the artifact.

          Checksum file is attached to this release.

          ISO Filename: ${{ steps.build.outputs.iso_name }}
        draft: false
        prerelease: false
        files: |
          ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
