name: Build and Release Felux ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ARCH: x86_64
  IMAGE_NAME: felux
  IMAGE_REPO: ghcr.io/reisaraujo-miguel
  IMAGE_TAG: latest
  VERSION: ${{ github.sha }}
  VARIANT: Kinoite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build ISO
      uses: jasonn3/build-container-installer@v1.2.2
      id: build
      with:
        arch: ${{ env.ARCH }}
        image_name: ${{ env.IMAGE_NAME }}
        image_repo: ${{ env.IMAGE_REPO }}
        #image_tag: ${{ env.IMAGE_TAG }}
        version: ${{ env.VERSION }}
        #variant: ${{ env.VARIANT }}
        iso_name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ env.VERSION }}.iso

    - name: Get ISO version
      id: iso_version
      run: |
        ISO_VERSION=$(date +"%Y%m%d")
        echo "version=$ISO_VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.iso_version.outputs.version }}
        release_name: Felux ISO v${{ steps.iso_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload ISO
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.iso_path }}
        asset_name: ${{ steps.build.outputs.iso_name }}
        asset_content_type: application/octet-stream

    - name: Upload ISO Checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.iso_path }}-CHECKSUM
        asset_name: ${{ steps.build.outputs.iso_name }}-CHECKSUM
        asset_content_type: text/plain
